# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-02-14 21:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inscricao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servico', models.CharField(choices=[('Encanador', 'Encanador'), ('Manicure', 'Manicure'), ('Pedreiro', 'Pedreiro'), ('Cabelo', 'Cabelo'), ('Costura', 'Costura'), ('Eletricista', 'Eletricista'), ('Jardinagem', 'Jardinagem'), ('Outros', 'Outros')], max_length=100)),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=11, unique=True, verbose_name='CPF')),
                ('idade', models.IntegerField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefone', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'verbose_name': 'nome',
                'verbose_name_plural': 'nomes',
                'ordering': ['nome'],
            },
        ),
    ]
